### ISSUE TITLE
ImageSharp cant download

### ISSUE THREAD

**Issue by rommilg** [jonsagara/jQuery-File-Upload.AspNetCoreMvc#1]
replacment for 
  

no longer exists

**Comment by isakatirci** [comment]
![image](https://user-images.githubusercontent.com/19477372/66267730-577d7680-e83d-11e9-9e05-aac7110db2a4.png)

**Comment by jonsagara** [comment]
I just pushed changes that replace ImageSharp with SkiaSharp and Magick.NET (the latter used for resizing GIFs).
