### ISSUE TITLE
Create dynamically folder

### ISSUE THREAD

**Issue by saini0039** [jonsagara/jQuery-File-Upload.AspNetCoreMvc#3]
Hi

I have use ur classes to save images in folder, But I want create all folder dynamic. Please help

**Comment by jonsagara** [comment]
Have a look at the `UploadWholeFileAsync` method, which is where the directories and files are created.

In particular, you would probably modify [this line](https://github.com/jonsagara/jQuery-File-Upload.AspNetCoreMvc/blob/master/src/jQuery-File-Upload.AspNetCoreMvc/Models/FileUpload/FileUploadUpload.cs#L73) to ensure your dynamic directories are created if they don't already exist.

Also, modify [this line](https://github.com/jonsagara/jQuery-File-Upload.AspNetCoreMvc/blob/master/src/jQuery-File-Upload.AspNetCoreMvc/Models/FileUpload/FileUploadUpload.cs#L86) to add your dynamic directory to the storage path.
